spring.application.name=hospitalManagement

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/hospitalDB
spring.datasource.username=hospital
spring.datasource.password=hospital

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

server.servlet.context-path=/api/v1

#security config
spring.security.user.name = shivani
spring.security.user.password = pass

#HikariCP settings
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.maxLifetime=600000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.maximum-idle=5

#Logging settings
logging.level.com.zaxxer.hikari.HikariConfig = DEBUG
logging.level.com.zaxxer.hikari =TRACE

#second level cache
hibernate.cache.use_second_level_cache=true
hibernate.cache.use_query_cache=true
hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory