spring.application.name=hospitalManagement

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/hospitalDB
spring.datasource.username=hospital
spring.datasource.password=hospital

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

server.servlet.context-path=/api/v1

#security config
spring.security.user.name = shivani
spring.security.user.password = pass
